export const GET_LIST_PRODUCT="GET_LIST_PRODUCT"
export const GET_LIST_ISRECPRODUCT="GET_LIST_ISRECPRODUCT"
export const GET_LIST_ISBESTPRODUCT="GET_LIST_ISBESTPRODUCT"
export const GET_ONE_PRODUCT="GET_ONE-PRODUCT"
export const GET_BYCATEGORY_PRODUCT="PRODUCT_LIST_FAIL"



